### ISSUE TITLE
Python examples 1a and 1b work, but throw an error.

### ISSUE THREAD

**Issue by aleksei-korolev** [iotaledger/wallet.rs#1530]
## Bug description

When combining examples 1a and 1b, the script works, but throws an error after completing:

```
[aleksei-at-work@laptop p]$ python test.py
Account created: Alice
thread 'pool-thread-#2' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(SLIP10Derive(Ok([247, 206, 110, 91, 187, 16, 80, 92, 163, 222, 92, 117, 207, 47, 193, 137, 76, 228, 215, 155, 33, 79, 171, 235, 208, 159, 148, 173, 2, 72, 122, 235])))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/stronghold-utils-0.3.0/src/ask.rs:48:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Rust version

Which version of Rust are you running?

```
cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
```

## Version

Which version of the library are you using?

The latest `production`.

## Hardware specification

What hardware are you using?

- Operating system: Manjaro Linux
- RAM: 15 GiB
- Cores: 16
- Device: ASUS ZenBook

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Copy examples 1a and 1b into a single .py file in a new folder.
2. Create an `.env` file with `SH_PASSWORD="here is your super secure password"` 
3. Execute the .py script.

## Expected behaviour

```
[aleksei-at-work@laptop p]$ python test.py
Account created: Alice
```

## Actual behaviour

```
[aleksei-at-work@laptop p]$ python test.py
Account created: Alice
thread 'pool-thread-#2' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(SLIP10Derive(Ok([247, 206, 110, 91, 187, 16, 80, 92, 163, 222, 92, 117, 207, 47, 193, 137, 76, 228, 215, 155, 33, 79, 171, 235, 208, 159, 148, 173, 2, 72, 122, 235])))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/stronghold-utils-0.3.0/src/ask.rs:48:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Errors

With `RUST_BACKTRACE=1`:

```
[aleksei-at-work@laptop p]$ python test.py
Account created: Alice
thread 'pool-thread-#14' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(SLIP10Derive(Ok([195, 45, 59, 213, 43, 157, 173, 93, 1, 95, 221, 66, 232, 25, 250, 15, 97, 20, 79, 72, 2, 95, 171, 67, 72, 190, 44, 217, 134, 206, 138, 247])))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/stronghold-utils-0.3.0/src/ask.rs:48:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: <stronghold_utils::ask::AskActor<Msg> as riker::actor::Actor>::recv
   4: riker::kernel::mailbox::run_mailbox
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: futures_executor::thread_pool::PoolState::work
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

With `RUST_BACKTRACE=full`:

```
[aleksei-at-work@laptop p]$ python test.py
Account created: Alice
thread 'pool-thread-#31' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(Ed25519PublicKey(Ok([31, 198, 241, 245, 0, 151, 239, 210, 39, 74, 118, 136, 199, 102, 86, 105, 139, 238, 142, 173, 155, 131, 251, 252, 29, 234, 230, 61, 33, 209, 205, 38])))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/stronghold-utils-0.3.0/src/ask.rs:48:42
stack backtrace:
   0:     0x7f66f4a3cbdd - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f66f4a3cbdd - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f66f4a3cbdd - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f66f4a3cbdd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f66f4a600dc - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x7f66f4a367d1 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x7f66f4a3e205 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f66f4a3e205 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f66f4a3e205 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x7f66f4a3df26 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x7f66f4a3e796 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x7f66f4a3e687 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x7f66f4a3d094 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f66f4a3e3b9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x7f66f379f053 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x7f66f379f143 - core::result::unwrap_failed::hc0baa33ef8bc7db8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
  16:     0x7f66f3e7554f - <stronghold_utils::ask::AskActor<Msg> as riker::actor::Actor>::recv::hcd1225f347fe6078
  17:     0x7f66f3cfaafc - riker::kernel::mailbox::run_mailbox::hb2468d0c4d908582
  18:     0x7f66f3d91f4b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h804ecd1c5eb6612a
  19:     0x7f66f48bdbb5 - futures_executor::thread_pool::PoolState::work::hde2a2a7d1360dfaa
  20:     0x7f66f48bed54 - std::sys_common::backtrace::__rust_begin_short_backtrace::h661e575b305a0fcd
  21:     0x7f66f48c1f78 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hab2f052576dd2cc8
  22:     0x7f66f4a41b83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1680342795a2dc08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  23:     0x7f66f4a41b83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45204a69827b0e83
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  24:     0x7f66f4a41b83 - std::sys::unix::thread::Thread::new::thread_start::h5d4e11bbda4161c8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7f66f59f78fd - <unknown>
  26:     0x7f66f5a79a60 - <unknown>
  27:                0x0 - <unknown>
```

The script in question:

```py
# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0


import iota_wallet as iw
import os
from dotenv import load_dotenv


# Load the env variables
load_dotenv()

# Get the stronghold password
STRONGHOLD_PASSWORD = os.getenv('SH_PASSWORD')

account_manager = iw.AccountManager(
    storage_path='./alice-database'
)  # note: `storage` and `storage_path` have to be declared together

account_manager.set_stronghold_password(STRONGHOLD_PASSWORD)

# mnemonic (seed) should be set only for new storage
# once the storage has been initialized earlier then you should omit this step
account_manager.store_mnemonic("Stronghold")

# general Tangle specific options
client_options = {
    "nodes": [
        {
            "url": "https://api.thin-hornet-0.h.chrysalis-devnet.iota.cafe",
            "auth": None,
            "disabled": False
        }
    ],
    "local_pow": True
}

# an account is generated with the given alias via `account_initialiser`
account_initialiser = account_manager.create_account(client_options)
account_initialiser.alias('Alice')

# initialise account based via `account_initialiser`
# store it to db and sync with Tangle
account = account_initialiser.initialise()
print(f'Account created: {account.alias()}')
```

**Comment by Thoralf-M** [comment]
Just commenting what I found:
It's caused by the polling which generates addresses and then the result isn't processed properly anymore, because everything gets dropped (just not in the right order it seems)
I added some logs to the derive function where it panics https://github.com/iotaledger/wallet.rs/blob/6c524b791bf8cb21d2470b6cc8127d53b64c5b4d/src/stronghold.rs#L538
![image](https://user-images.githubusercontent.com/46689931/205037703-a320b6fc-b13e-4829-b537-c05e0bff5808.png) and two to the account manager drop
```Rust
impl Drop for AccountManager {
    fn drop(&mut self) {
        println!("dropping account manager");
        self.stop_background_sync().unwrap();
        println!("dropped account manager");
    }
}
```
the output of this is then
```
Account created: [{'address': {'inner': 'atoi1qp2xcvlug2dn3vdazl5aujjry6h9ee9t39wsr5e6v8akq057znnajfrm340'}, 'balance': 0, 'key_index': 0, 'internal': False, 'outputs': {}}]
slip10 derive 0
slip10 derive 1
slip10 derive 2
slip10 derive 3
slip10 derive 0
dropping account manager
thread 'pool-thread-#31' panicked at 'called `Result::unwrap()` on an `Err` value: ReturnControlRequest(SLIP10Derive(Ok([61, 36, 241, 150, 141, 32, 138, 152, 216, 143, 72, 248, 77, 239, 31, 148, 153, 210, 103, 205, 115, 229, 7, 226, 254, 61, 82, 170, 73, 12, 54, 244])))', /home/t/.cargo/registry/src/github.com-1ecc6299db9ec823/stronghold-utils-0.3.0/src/ask.rs:48:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
dropped account manager
```

And the ask function from stronghold panics here https://github.com/iotaledger/stronghold.rs/blob/b7fb5e9453883b3ff23d935e4e581517c42c098c/utils/src/ask.rs#L26-L29
because there is no error handling :cry:

**Comment by samuel-rufi** [comment]
One option to maybe solve this would be to avoid the drop of the handle. However Thoralf and I weren't able to find out how to avoid this drop best. At this point, we don't want to spend more resources on this, since the used stronghold version is quite old and the shimmer develop codebase diverges much.
